source 'https://rubygems.org'

gem 'sinatra', '~> 4.1.1'
gem 'singlogger'
gem 'redcarpet', '~> 3.6.1'
gem 'safe_yaml', '~>1.0.5'
gem 'rackup', '~>2.2.1'
gem 'puma', '~>6.6.0'

gem 'rubocop', '~>1.73.2'
